name: AQX Trading Platform Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      test_suite:
        description: 'Test suite to run'
        required: true
        default: 'smoke'
        type: choice
        options:
        - smoke
        - critical
        - trading
        - all

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: 'pip'
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          chromium-browser \
          chromium-chromedriver \
          xvfb \
          x11-utils
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Create test directories
      run: |
        mkdir -p screenshots reports logs test_data
        touch screenshots/.gitkeep reports/.gitkeep logs/.gitkeep
    
    - name: Set Chrome environment
      run: |
        echo "CHROME_BIN=/usr/bin/chromium-browser" >> $GITHUB_ENV
        echo "CHROMEDRIVER_PATH=/usr/bin/chromedriver" >> $GITHUB_ENV
    
    - name: Run tests
      run: |
        xvfb-run -a --server-args="-screen 0 1920x1080x24" \
        python run_tests.py --type ${{ github.event.inputs.test_suite || 'smoke' }} --headless
      continue-on-error: true
    
    - name: Generate dashboard
      if: always()
      run: |
        python scripts/generate_dashboard.py
      continue-on-error: true
    
    - name: List generated files
      if: always()
      run: |
        echo "=== Reports Directory ==="
        ls -la reports/ || echo "No reports directory"
        echo "=== Screenshots Directory ==="
        ls -la screenshots/ || echo "No screenshots directory"
        echo "=== Current Directory ==="
        ls -la
    
    - name: Upload test artifacts
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results-${{ github.run_number }}
        path: |
          reports/
          screenshots/
          logs/
        retention-days: 30
        if-no-files-found: warn
    
    - name: Upload test reports
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: html-reports-${{ github.run_number }}
        path: |
          reports/*.html
          reports/*.json
        retention-days: 30
        if-no-files-found: warn
    
    - name: Test Summary
      if: always()
      run: |
        echo "🧪 Test Execution Summary"
        echo "========================"
        echo "Workflow: ${{ github.workflow }}"
        echo "Run Number: ${{ github.run_number }}"
        echo "Test Suite: ${{ github.event.inputs.test_suite || 'smoke' }}"
        echo "Branch: ${{ github.ref_name }}"
        echo "Commit: ${{ github.sha }}"
        
        if [ -f "reports/test_summary.json" ]; then
          echo "Test results found:"
          cat reports/test_summary.json
        else
          echo "No test summary found"
        fi